import { createCipheriv, createHmac, createHash, randomBytes, timingSafeEqual } from 'node:crypto';
import { env } from '../config/env.js';

type OAuthState={userId:string;workspaceId:string;returnUrl:string;expiresAt:number;nonce:string};
type MetaError={error?:{message?:string;type?:string;code?:number}};
type MetaToken=MetaError&{access_token?:string;token_type?:string;expires_in?:number};
export type MetaPage={id:string;name:string;access_token:string;instagram_business_account?:{id:string;username?:string;name?:string;profile_picture_url?:string}};
type MetaPages=MetaError&{data?:MetaPage[];paging?:{next?:string}};

const stateKey=()=>createHash('sha256').update(`${env.JWT_SECRET}:meta-state`).digest();
const tokenKey=()=>createHash('sha256').update(`${env.JWT_SECRET}:social-token`).digest();
const encode=(value:Buffer|string)=>Buffer.from(value).toString('base64url');
function assertConfigured(){if(!env.META_APP_ID||!env.META_APP_SECRET||!env.META_REDIRECT_URI)throw Object.assign(new Error('Meta connection is not configured on the server'),{statusCode:503})}
function allowedReturnUrl(value:string){return value.startsWith('vyradee://')||value.startsWith('exp://')||value.startsWith('http://localhost')||value.startsWith('http://127.0.0.1')}
export function createMetaState(input:Omit<OAuthState,'expiresAt'|'nonce'>){if(!allowedReturnUrl(input.returnUrl))throw Object.assign(new Error('Unsupported app return URL'),{statusCode:400});const payload:OAuthState={...input,expiresAt:Date.now()+10*60_000,nonce:randomBytes(16).toString('hex')};const encoded=encode(JSON.stringify(payload));const signature=encode(createHmac('sha256',stateKey()).update(encoded).digest());return`${encoded}.${signature}`}
export function verifyMetaState(value:string){const[encoded,signature]=value.split('.');if(!encoded||!signature)throw Object.assign(new Error('Invalid OAuth state'),{statusCode:400});const expected=createHmac('sha256',stateKey()).update(encoded).digest();const actual=Buffer.from(signature,'base64url');if(actual.length!==expected.length||!timingSafeEqual(actual,expected))throw Object.assign(new Error('Invalid OAuth state'),{statusCode:400});const payload=JSON.parse(Buffer.from(encoded,'base64url').toString('utf8')) as OAuthState;if(payload.expiresAt<Date.now()||!allowedReturnUrl(payload.returnUrl))throw Object.assign(new Error('OAuth state expired'),{statusCode:400});return payload}
export function getMetaAuthorizationUrl(state:string){assertConfigured();const url=new URL(`https://www.facebook.com/${env.META_GRAPH_VERSION}/dialog/oauth`);url.searchParams.set('client_id',env.META_APP_ID!);url.searchParams.set('redirect_uri',env.META_REDIRECT_URI!);url.searchParams.set('state',state);url.searchParams.set('response_type','code');url.searchParams.set('auth_type','rerequest');url.searchParams.set('scope',['pages_show_list','pages_read_engagement','pages_manage_posts','instagram_basic','instagram_content_publish'].join(','));return url.toString()}
async function readJson<T>(url:string){const response=await fetch(url,{headers:{Accept:'application/json'}});const data=await response.json() as T&MetaError;if(!response.ok||data.error?.message)throw Object.assign(new Error(data.error?.message??'Meta request failed'),{statusCode:502});return data as T}
export async function exchangeMetaCode(code:string){assertConfigured();const shortUrl=new URL(`https://graph.facebook.com/${env.META_GRAPH_VERSION}/oauth/access_token`);shortUrl.searchParams.set('client_id',env.META_APP_ID!);shortUrl.searchParams.set('client_secret',env.META_APP_SECRET!);shortUrl.searchParams.set('redirect_uri',env.META_REDIRECT_URI!);shortUrl.searchParams.set('code',code);const short=await readJson<MetaToken>(shortUrl.toString());if(!short.access_token)throw Object.assign(new Error('Meta did not return an access token'),{statusCode:502});const longUrl=new URL(`https://graph.facebook.com/${env.META_GRAPH_VERSION}/oauth/access_token`);longUrl.searchParams.set('grant_type','fb_exchange_token');longUrl.searchParams.set('client_id',env.META_APP_ID!);longUrl.searchParams.set('client_secret',env.META_APP_SECRET!);longUrl.searchParams.set('fb_exchange_token',short.access_token);const long=await readJson<MetaToken>(longUrl.toString());return{accessToken:long.access_token??short.access_token,expiresIn:long.expires_in??short.expires_in}}
export async function getMetaPages(userAccessToken:string){let next:string|undefined;const pages:MetaPage[]=[];do{const url=next?new URL(next):new URL(`https://graph.facebook.com/${env.META_GRAPH_VERSION}/me/accounts`);if(!next){url.searchParams.set('fields','id,name,access_token,instagram_business_account{id,username,name,profile_picture_url}');url.searchParams.set('limit','100');url.searchParams.set('access_token',userAccessToken)}const result=await readJson<MetaPages>(url.toString());pages.push(...(result.data??[]));next=result.paging?.next}while(next);return pages.filter(page=>page.id&&page.name&&page.access_token)}
export function sealSocialToken(token:string){const iv=randomBytes(12);const cipher=createCipheriv('aes-256-gcm',tokenKey(),iv);const encrypted=Buffer.concat([cipher.update(token,'utf8'),cipher.final()]);const tag=cipher.getAuthTag();return`v1.${encode(iv)}.${encode(tag)}.${encode(encrypted)}`}